# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://yoursite.com
title: West Virginia Forest Carbon Credit Estimator
email: cwalte12@mail.wvu.edu
author: Chris Walter
description: > # "Estimate carbon credits for forested land in West Virgina, USA. 
  You can edit this line in _config.yml. It will appear in your document 
  head meta (for Google search results) and in your feed.xml site 
  description.
copyright: 'Copyright &copy; 2021 Chris Walter. All Rights Reserved.'
credits: 'The carbon credit estimator is a free to use, open source tool created at West Virginia University.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #


